#pragma once

#include <util/system/defaults.h>

enum HttpCodes {
    HTTP_CONTINUE                      = 100,
    HTTP_SWITCHING_PROTOCOLS           = 101,

    HTTP_OK                            = 200,
    HTTP_CREATED                       = 201,
    HTTP_ACCEPTED                      = 202,
    HTTP_NON_AUTHORITATIVE_INFORMATION = 203,
    HTTP_NO_CONTENT                    = 204,
    HTTP_RESET_CONTENT                 = 205,
    HTTP_PARTIAL_CONTENT               = 206,

    HTTP_MULTIPLE_CHOICES              = 300,
    HTTP_MOVED_PERMANENTLY             = 301,
    HTTP_FOUND                         = 302,
    HTTP_SEE_OTHER                     = 303,
    HTTP_NOT_MODIFIED                  = 304,
    HTTP_USE_PROXY                     = 305,
    HTTP_TEMPORARY_REDIRECT            = 307,

    HTTP_BAD_REQUEST                   = 400,
    HTTP_UNAUTHORIZED                  = 401,
    HTTP_PAYMENT_REQUIRED              = 402,
    HTTP_FORBIDDEN                     = 403,
    HTTP_NOT_FOUND                     = 404,
    HTTP_METHOD_NOT_ALLOWED            = 405,
    HTTP_NOT_ACCEPTABLE                = 406,
    HTTP_PROXY_AUTHENTICATION_REQUIRED = 407,
    HTTP_REQUEST_TIME_OUT              = 408,
    HTTP_CONFLICT                      = 409,
    HTTP_GONE                          = 410,
    HTTP_LENGTH_REQUIRED               = 411,
    HTTP_PRECONDITION_FAILED           = 412,
    HTTP_REQUEST_ENTITY_TOO_LARGE      = 413,
    HTTP_REQUEST_URI_TOO_LARGE         = 414,
    HTTP_UNSUPPORTED_MEDIA_TYPE        = 415,
    HTTP_REQUESTED_RANGE_NOT_SATISFIABLE = 416,
    HTTP_EXPECTATION_FAILED            = 417,
    HTTP_UNPROCESSABLE_ENTITY          = 422,

    HTTP_INTERNAL_SERVER_ERROR         = 500,
    HTTP_NOT_IMPLEMENTED               = 501,
    HTTP_BAD_GATEWAY                   = 502,
    HTTP_SERVICE_UNAVAILABLE           = 503,
    HTTP_GATEWAY_TIME_OUT              = 504,
    HTTP_HTTP_VERSION_NOT_SUPPORTED    = 505,

    // Custom
    HTTP_EXTENDED                      = 1000,
    HTTP_BAD_RESPONSE_HEADER           = 1000,
    HTTP_CONNECTION_LOST               = 1001,
    HTTP_BODY_TOO_LARGE                = 1002,
    HTTP_ROBOTS_TXT_DISALLOW           = 1003,
    HTTP_BAD_URL                       = 1004,
    HTTP_BAD_MIME                      = 1005,
    HTTP_DNS_FAILURE                   = 1006,
    HTTP_BAD_STATUS_CODE               = 1007,
    HTTP_BAD_HEADER_STRING             = 1008,
    HTTP_BAD_CHUNK                     = 1009,
    HTTP_CONNECT_FAILED                = 1010,
    HTTP_FILTER_DISALLOW               = 1011,
    HTTP_LOCAL_EIO                     = 1012,
    HTTP_BAD_CONTENT_LENGTH            = 1013,
    HTTP_BAD_ENCODING                  = 1014,
    HTTP_LENGTH_UNKNOWN                = 1015,
    HTTP_HEADER_EOF                    = 1016,
    HTTP_MESSAGE_EOF                   = 1017,
    HTTP_CHUNK_EOF                     = 1018,
    HTTP_PAST_EOF                      = 1019,
    HTTP_HEADER_TOO_LARGE              = 1020,
    HTTP_URL_TOO_LARGE                 = 1021,
    HTTP_INTERRUPTED                   = 1022,
    HTTP_CUSTOM_NOT_MODIFIED           = 1023,
    HTTP_BAD_CONTENT_ENCODING          = 1024,
    HTTP_NO_RESOURCES                  = 1025,
    HTTP_FETCHER_SHUTDOWN              = 1026,
    HTTP_CHUNK_TOO_LARGE               = 1027,
    HTTP_SERVER_BUSY                   = 1028,
    HTTP_SERVICE_UNKNOWN               = 1029,
    HTTP_PROXY_UNKNOWN                 = 1030,
    HTTP_PROXY_REQUEST_TIME_OUT        = 1031,
    HTTP_PROXY_INTERNAL_ERROR          = 1032,
    HTTP_PROXY_CONNECT_FAILED          = 1033,
    HTTP_PROXY_CONNECTION_LOST         = 1034,
    HTTP_PROXY_NO_PROXY                = 1035,
    HTTP_PROXY_ERROR                   = 1036,
    HTTP_CODE_MAX
};

const char* HttpCodeStr(int code);
